version: '3'
services:
  frontend:
    image: frontend-image
    build: ./frontend
    ports: 
      - 80:3000
    environment:
      env_file: development.env
  frontend-hot-reload:
    image: frontend-image
    build: ./frontend
    ports: 
      - 80:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      env_file: ./frontend/.env
  backend:
    image: backend-image
    build: ./backend
    ports:
      - "8000:8000"
