version: '3'
services:
  frontend:
    image: frontend-image
    build: ./frontend
    restart: always
    ports: 
      - 3000:3000
    environment:
      env_file: ./frontend/.env.development
  frontend-hot-reload:
    image: frontend-image
    build: ./frontend
    ports: 
      - 80:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      env_file: ./frontend/.env.development
  backend:
    image: backend-image
    build: ./backend
    restart: always
    volumes:
      - /srv/media/:/srv/media/
    ports: 
      - 8000:8000
