services:
  frontend:
    image: frontend-image
    build: ./frontend
    ports: 
      - 80:3000
  backend:
    image: backend-image
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
