POST http://books-front.colab.duke.edu:8000/api/v1/auth/token/
content-type: application/json

{
    "email": "crs79@duke.edu",
    "password": "120g018;'c.zk"
}
###

POST http://books-front.colab.duke.edu:8000/api/v1/auth/users/
content-type: application/json

{
    "user-registration": {
        "email": "crs79@duke.edu",
        "username": "crs79",
        "password": "120g018;'c.zk"
    }
}