# Generated by Django 4.1.6 on 2023-02-25 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('books', '0013_alter_bookimage_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_vendors', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('unit_buyback_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_books', to='books.book')),
                ('buyback_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buybacks', to='buybacks.buybackorder')),
            ],
        ),
    ]
