# Generated by Django 4.1.6 on 2023-03-09 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buybacks', '0002_rename_cost_buyback_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bb_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
