# Generated by Django 4.1.5 on 2023-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleReconcilitation',
            new_name='SalesReconciliation',
        ),
    ]
