# Generated by Django 4.1.5 on 2023-01-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_salereconcilitation_salesreconciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='books',
            new_name='book',
        ),
    ]
