# Generated by Django 4.1.5 on 2023-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('sales', '0002_alter_sale_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='book',
        ),
        migrations.AddField(
            model_name='sale',
            name='book',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
