# Generated by Django 4.1.5 on 2023-02-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('sales', '0003_remove_sale_book_sale_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='book',
        ),
        migrations.AddField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.book'),
            preserve_default=False,
        ),
    ]
