# Generated by Django 4.1.5 on 2023-01-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_name_alter_book_authors_and_more'),
        ('sales', '0003_rename_books_sale_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', to_field='isbn_13'),
        ),
    ]
