# Generated by Django 4.1.5 on 2023-01-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_id_alter_book_isbn_13'),
        ('sales', '0004_alter_sale_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreconciliation',
            name='sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_reconciliation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.salesreconciliation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
