# Generated by Django 4.1.5 on 2023-02-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='book',
            new_name='book_id',
        ),
    ]
