# Generated by Django 4.1.7 on 2023-04-13 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_salesreconciliation_is_sales_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreconciliation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
