# Generated by Django 4.1.5 on 2023-02-01 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('isbn_10', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=50)),
                ('publishedDate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(0)])),
                ('pageCount', models.PositiveIntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('thickness', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('authors', models.ManyToManyField(to='books.author')),
                ('genres', models.ManyToManyField(to='books.genre')),
            ],
        ),
    ]
