# Generated by Django 4.1.5 on 2023-01-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page_cnt',
            new_name='pageCount',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='publishedDate',
        ),
    ]
