# Generated by Django 4.1.5 on 2023-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('books', '0003_alter_book_height_alter_book_pagecount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='genres.genre'),
        ),
    ]
