# Generated by Django 4.1.5 on 2023-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_genre_alter_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isGhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
