# Generated by Django 4.1.5 on 2023-01-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_name_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
