# Generated by Django 4.1.6 on 2023-03-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_height_alter_book_pagecount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookimage',
            old_name='url',
            new_name='image_url',
        ),
    ]
