# Generated by Django 4.1.6 on 2023-03-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_relatedbookgroup_book_related_books_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='related_books_group',
            new_name='related_book_group',
        ),
    ]
