# Generated by Django 4.1.7 on 2023-03-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_bookinventorycorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinventorycorrection',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_correction_book', to='books.book'),
        ),
    ]
