# Generated by Django 4.1.7 on 2023-03-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_bookinventorycorrection_book'),
        ('books', '0018_rename_related_books_group_book_related_book_group'),
    ]

    operations = [
    ]
