# Generated by Django 4.1.7 on 2023-03-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0016_alter_bookimage_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField()),
                ('bookcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_designer.bookcase')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_mode', models.CharField(choices=[('SO', 'Spine Out'), ('CO', 'Cover Out')], max_length=50)),
                ('display_count', models.PositiveIntegerField()),
                ('ordering', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_designer.shelf')),
            ],
        ),
    ]
