# Generated by Django 4.1.7 on 2023-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayedbook',
            name='display_mode',
            field=models.CharField(choices=[('Spine Out', 'Spine Out'), ('Cover Out', 'Cover Out')], max_length=50),
        ),
    ]
