# Generated by Django 4.1.7 on 2023-03-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_bookimage_book'),
        ('case_designer', '0002_alter_displayedbook_display_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayedbook',
            old_name='ordering',
            new_name='display_order',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='ordering',
            new_name='shelf_order',
        ),
        migrations.AlterField(
            model_name='displayedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayed_books', to='books.book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='bookcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='case_designer.bookcase'),
        ),
    ]
