# Generated by Django 4.1.7 on 2023-03-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_designer', '0004_alter_displayedbook_book_alter_displayedbook_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcase',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
