# Generated by Django 4.1.7 on 2023-03-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_designer', '0005_bookcase_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcase',
            name='last_editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcase',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcase_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
