# Generated by Django 4.1.5 on 2023-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_genre_book_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='book_cnt',
            field=models.PositiveIntegerField(),
        ),
    ]
