# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on: [pull_request]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        working-directory: ./frontend
        run: npm install

      
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint_dir: ./frontend
          eslint_extensions: tsx
          eslint: true
          eslint_args: "--max-warnings 0"
          prettier_dir: ./frontend
          prettier_extensions: tsx
          prettier: true
          prettier_args: "--max-warnings 0"
          tsc_dir: ./frontend
          tsc: true
        


